#! /bin/expect -f
set timeout 300
spawn /var/opt/MicroStrategy/bin/mstrcfgwiz-editor
send -- "\r"
expect -exact "->"
send -- "2\r"
expect -exact "->"
send -- "1\r"
expect -exact "Do you want to create Metadata Tables (Y/N) \[Y\]->"
send -- "Y\r"
expect -exact "->"
send -- "3\r"
expect -exact "ODBC Login->"
send -- "mstrmeta\r"
expect -exact "ODBC Password->"
send -- MSTRMETADBKEY\r"
expect -exact "Metadata Prefix (optional)->"
send -- "MD_\r"
expect -exact "Metadata script location path \[mdmysql.sql\] ->"
send -- "\r"
expect -exact "Do you want to create History List tables (Y/N) \[Y\] ?"
send -- "Y\r"
expect -exact "\r"
send -- "N\r"
expect -exact "->"
send -- "2\r"
expect -exact "ODBC Login->"
send -- "mstrhist\r"
expect -exact "ODBC Password->"
send -- MSTRHISTDBKEY\r"
expect -exact "History Prefix (optional)->"
send -- "HL_\r"
expect -exact "History script location path \[content_server_db_MySQL.sql\] ->"
send -- "\r"
expect -exact "Do you want to create Statistics & Enterprise Manager Repositories (Y/N) \[Y\]?"
send -- "Y\r"
expect -exact "->"
send -- "4\r"
expect -exact "ODBC Login->"
send -- "mstrstats\r"
expect -exact "ODBC Password->"
send -- MSTRSTATSDBKEY\r"
expect -exact "Statistics & Enterprise Manager script location path \[CreateTablesScript.sql\] ->"
send -- "\r"
expect -exact "Response file to be saved \[Response.ini\] ->"
send -- "iserver_repositories.ini\r"
expect -exact "Do you want to execute the response file just created? (Y/N) \[Y\]->"
send -- "Y\r"
expect eof